name: sockjs_client_wrapper
version: 1.1.5
description: A Dart wrapper for the `sockjs-client` JS library.
homepage: https://github.com/Workiva/sockjs_client_wrapper

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  js: ^0.6.3
  w_common:
    git:
      url: https://github.com/skawa-universe/w_common.git
      ref: su/nnbd

dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  build_web_compilers: ^3.2.2
#  dart_dev:
#    path: ../dart_dev
#  dependency_validator: ^2.0.1
  test: ^1.15.7
  workiva_analysis_options: ^1.1.0
